name = "zentask"
compatibility_date = "2024-04-28"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".next"

[build]
command = "npm run build"

[vars]
# Các biến môi trường Public
NEXT_PUBLIC_APP_URL = "https://zentask.pages.dev"
